requires 'URI';
requires 'Data::Dump';
# requires 'Modern::Perl', '1.20120521';
requires 'Mojolicious::Lite';
requires 'Imager::File::JPEG';
requires 'Imager::File::PNG';
#requires 'Wight'; # needs phantomjs package installed to install